### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by torchsmith** [sgb-io/jquery.circular-carousel#4]
I'm following the demo exactly trying to set this up, but I'm using a much more recent version of jQuery, whereas this shows it using v1.11.0. Is there any compatibility issues in the actual carousel between jQuery versions? If so, is there an easy way to adjust it?

Thanks,
Isaac

**Comment by sgb-io** [comment]
Hi @torchsmith - the library is very old (over 8 years) and is not being actively maintained. Unfortunately at the time I did not record what version of jQuery was used at the time.

I would suggest the source could desperately do with being re-written. Unfortunately I don't have time for this right now but I would happily review any PRs.

You could look at swapping out just the jQuery pieces for upgraded code, if you don't have the time to re-write

**Comment by torchsmith** [comment]
Closing as project has been abandoned.
